using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BAPBAPBalanceMod
{
    public enum CharacterID
    {
        KITSU = 0,
        ANNA = 1,
        CHUCK = 2,
        SASHIMI = 3,
        KIDDO = 4,
        ZOOK = 5,
        SKINNY = 6,
        FROGGY = 7,
        TEEVEE = 8,
        SOFIA = 9,
        JIRO = 10,
        BISHOP = 11,
        EVE = 12,
        KAT = 13,
        ROCKY = 14,
    }


    public enum AugmentID
    {
        P_CHARAUGMENT_ANNA_DASHOVERDRIVE = 16,
        P_CHARAUGMENT_ANNA_DIEDIEDIE = 17,
        P_CHARAUGMENT_ANNA_MACHINEGUN = 20,
        P_CHARAUGMENT_ANNA_PRECISIONSHOT = 21,
        P_ONHIT_LMB_RESETBULLETS = 22,

        P_CHARAUGMENT_BISHOP_HPSTACKS = 24,
        P_CHARAUGMENT_BISHOP_MOUTHRANGE = 25,
        P_CHARAUGMENT_BISHOP_MUNCH = 26,
        P_CHARAUGMENT_BISHOP_TETHERCOUNTER = 28,

        P_CHARAUGMENT_CHUCK_CHUCKRESET = 29,
        P_CHARAUGMENT_CHUCK_DUCKYJUMP = 30,
        P_CHARAUGMENT_CHUCK_CHUCK_HUG = 31,
        P_CHARAUGMENT_CHUCK_LOCKERSLAM = 32,
        P_CHARAUGMENT_CHUCK_RAIDBOSS = 34,

        P_CHARAUGMENT_EVE_EXPLOSIVEICEBLOCK = 36,
        P_CHARAUGMENT_EVE_FREEZINGHEAL = 37,
        P_CHARAUGMENT_EVE_ICEBLOCKSLIDE = 38,
        P_CHARAUGMENT_EVE_ICESKATING = 39,

        P_CHARAUGMENT_FROGGY_BIGSWAMP = 40,
        P_CHARAUGMENT_FROGGY_DASHEXECUTE = 41,
        P_CHARAUGMENT_FROGGY_HEALINGHOP = 42,
        P_CHARAUGMENT_FROGGY_HEALTHYLEAP = 43,
        P_CHARAUGMENT_FROGGY_HEALTHYTONGUE = 44,
        P_CHARAUGMENT_FROGGY_HIPPITYHOP = 45,
        P_CHARAUGMENT_FROGGY_LICKYWICKY = 46,
        P_CHARAUGMENT_FROGGY_TONGUEPULL = 48,

        P_CHARAUGMENT_JIRO_CONCUSS = 51,
        P_CHARAUGMENT_JIRO_DEFLECTINGKICK = 52,
        P_CHARAUGMENT_JIRO_DOORDASH = 53,
        P_CHARAUGMENT_JIRO_LMBDASH = 56,
        P_CHARAUGMENT_JIRO_TASTYFOOD = 57,

        P_CHARAUGMENT_KAT_AGGROCATS = 58,
        P_CHARAUGMENT_KAT_POLYMORPHHEAL = 59,
        P_CHARAUGMENT_KAT_QRECAST = 60,
        P_CHARAUGMENT_KAT_ULTHEALINGCATS = 61,

        P_CHARAUGMENT_KIDDO_AUTOSHIELD = 62,
        P_CHARAUGMENT_KIDDO_BLAZINGCRATOR = 63,
        P_CHARAUGMENT_KIDDO_CALAMITYMETEOR = 64,
        P_CHARAUGMENT_KIDDO_METEORSHOWER = 66,
        P_CHARAUGMENT_KIDDO_RISINGFLAME = 67,
        P_CHARAUGMENT_KIDDO_THORNSHIELD = 68,

        P_CHARAUGMENT_BOUNCEPROJECTILE = 75,
        P_CHARAUGMENT_BOUNCEPROJECTILE_KITSU_ULT = 76,
        P_CHARAUGMENT_EXPLOSIVE_JUMP = 77,
        P_CHARAUGMENT_EXTRAMILEAGE = 78,
        P_CHARAUGMENT_FOXTRAP = 79,
        P_CHARAUGMENT_KITSU_CHARGE_PULSAR = 81,
        P_CHARAUGMENT_KITSU_TRILUNARBARRAGE = 84,
        P_CHARAUGMENT_KITSU_VANISH = 86,
        P_CHARAUGMENT_KITSU_ULTTRAIL = 85,
        P_CHARAUGMENT_SCATTERSHOT_1 = 88,
        P_CHARAUGMENT_SCATTERSHOT_2 = 89,
        P_CHARAUGMENT_ULTRAVIOLET = 93,

        P_DAMAGINGATKSPEED = 94, // Stop hitting yourself?
        P_ONTAKEDMG_QDMG = 96, // Slingshot thingy?

        P_CHARAUGMENT_ROCKY_BOULDERING = 97,
        P_CHARAUGMENT_ROCKY_CHARGEDSHOT = 98,
        P_CHARAUGMENT_ROCKY_MUSCLE = 99,
        P_CHARAUGMENT_ROCKY_RECAST = 100,
        P_ONCD_MOUNTAINSHIELD = 101,

        P_AURA_SPAWN_JELLYFISH = 102,
        P_CHARAUGMENT_SASHIMI_BOUNCEROLL = 104,
        P_CHARAUGMENT_SASHIMI_EARTHQUAKE = 106,
        P_CHARAUGMENT_SASHIMI_ONCD_BUBBLEMODULE = 108,
        P_CHARAUGMENT_SASHIMI_OVERCHARGE = 109,
        P_CHARAUGMENT_SASHIMI_SHIELDROLL = 110,
        P_CHARAUGMENT_SASHIMI_SLAMSTUN = 111,
        P_CHARAUGMENT_SASHIMI_TELEPORTATIONMODULE = 112,

        P_CHARAUGMENT_SKINNY_360SCYTHE = 113,
        P_CHARAUGMENT_SKINNY_BIGSCYTHE = 114,
        P_CHARAUGMENT_SKINNY_LONGCONAMBUSH = 116,
        P_CHARAUGMENT_SKINNY_RESTEALTH = 117,
        P_CHARAUGMENT_SKINNY_SEISMICSLASH = 119,
        P_CHARAUGMENT_SKINNY_SLEEP = 120,
        P_CHARAUGMENT_SKINNY_SNEAK = 121,

        P_CHARAUGMENT_SOFIA_BURNINGDASH = 122,
        P_CHARAUGMENT_SOFIA_COMBUSTION = 123,
        P_CHARAUGMENT_SOFIA_FIREYCOUNTER = 125,
        P_CHARAUGMENT_SOFIA_FLAMEPORTAL = 126,

        P_CHARAUGMENT_TEEVEE_CLONE_DURATION = 130,
        P_CHARAUGMENT_TEEVEE_CLONEAOE = 132,
        P_CHARAUGMENT_TEEVEE_EXTRASWAP = 134,
        P_CHARAUGMENT_TEEVEE_EXTRACLONE = 141,

        P_CHARAUGMENT_ZOOK_CHARGEDSHOT = 143,
        P_CHARAUGMENT_ZOOK_MINETURRET = 146,
        P_CHARAUGMENT_ZOOK_MOREMINES = 147,
        P_CHARAUGMENT_ZOOK_PERMAHOMING = 149,

        P_DAMAGECAP = 151,
        P_DAMAGECAPSTUN = 152,
        P_XTRAXTRABULK = 156,

        P_FIREBALL = 157,
        P_FIREWAVE = 158,
        P_FIREWAVE_BURN = 160,
        P_FIREWAVE_COOLDOWN = 161,
        P_FIREWAVE_NOABILITIES = 163,

        P_FIREWAVE_RANGE = 166,
        P_ONHIT_LIGHTNING_SPRINT = 175,
        P_ONHIT_LIGHTNINGSTRIKE_ABILITIES = 177,
        P_ONHIT_LIGHTNINGSTRIKE_LMB = 179,
        P_BLOOD_EXTRADMG = 191,
        P_BLOOD_LIFESTEAL = 192,
        P_ONCD_BLEED = 203,
        P_GIVE_ITEM_CHAINS = 208,
        P_GIVE_ITEM_DASH = 209,
        P_GIVE_ITEM_GRAVITYPULL = 211,
        P_GIVE_ITEM_HPBONUS = 212,
        P_GIVE_ITEM_KNOCKBACK = 213,
        P_GIVE_ITEM_PROTECTZONE = 214,
        P_GIVE_ITEM_REBOOT = 215,
        P_GIVE_ITEM_VIRUS = 216,
        P_SPAWNENTITY_SLIMEBOSS = 217,
        P_ATMASBAG = 225,
        P_AURA_ORBIT = 226,
        P_BERSERK = 230,
        P_BUFF_HP_LOSEDMG = 235,
        P_BUFF_HP_LOSEMS = 236,
        P_BUFF_HPREGEN = 237,
        P_BUFF_WALKINGBOOTS = 238,
        P_CHARAUGMENT_CHUCK_TITANSTRADEOFF = 239,
        P_CRITICALABILITY = 247,
        P_CRITSHIELD = 250,
        P_DAMAGING_BLOW = 252,
        P_EXECUTIONER = 261,
        P_EXPLOSIVECHARM = 263,
        P_FIREYCAPE = 267,
        P_FRONTDAMAGEMITIGATE = 269,
        P_GAINSIZEBYHP_GIGANTICSIZE = 271,
        P_GRAVITATIONALORBIT_GIGANTICSIZE = 274,
        P_HEALINGRAIN = 277,
        P_HEALINGSKILLS = 278,
        P_HEAVYHITTER = 281,
        P_HITTYWITTY = 282,
        P_JELLYSPLASH = 286,
        P_KAMIKAZE = 290,
        P_KNOCKBACKPILLED = 291,
        P_LMBFORULT = 293,
        P_LUCKYDANCE = 295,
        P_METALULT = 299,
        P_ONUSE_DMG = 303,
        P_ONUSE_LMB_PUSH_SPEED = 305,
        P_ONUSE_ULT_DMG = 307,
        P_PRIMARYCHARGING = 315,
        P_PROTECTIVEBUBBLE = 318,
        P_RAGINGSPIRIT = 321,
        P_RAPIDFIRE = 322,
        P_RECHARNING_SHIELD = 324,
        P_SKULLSHIELD = 333,
        P_SPEEDYWEEDY = 342,
        P_STICKYBOMB = 346,
        P_STYLEFACTOR = 347,
        P_TAKEDOWN_TONIC = 350,
        P_THORNS = 351,
        P_TIMED_DMG = 352,
        P_TOXICTEMPO = 353,
        P_ULTIMATEHITTYWITTY = 356,
        P_VENGEANCE = 361,
        P_WATERSHIELD = 362,
        P_WINSOOSBLADE = 364,
        P_WORKBENCH = 365,
        P_XTRABULK = 367,
        P_ZOMBIETURRETS = 369,

        P_STAT_ATTACKSPEED = 375, // Attack Speed
        P_STAT_CDR = 376, // Cooldown Reduction
        P_STAT_CRITCHANCE = 377, // Crit Chance
        P_STAT_CRITDAMAGE = 378, // Crit Dmg
        P_STAT_DAMAGE = 379, // Damage
        P_STAT_DAMAGEREDUCTION = 380, // Unused
        P_STAT_HP = 381, // Health
        P_STAT_LIFESTEAL = 382, // Lifesteal
        P_STAT_MOVESPEED = 384, // Movement Speed
        P_STAT_MINOR_ATTACKSPEED = 389,
        P_STAT_MINOR_DAMAGE = 390,
        P_STAT_MINOR_HP = 391,
        P_CHARAUGMENT_EVE_FROSTDETONATION = 397,
        P_CHARAUGMENT_EVE_LONGSHOT = 398,
        P_CHARAUGMENT_FROGGY_EXTENDOTONGUE = 399,
        P_CHARAUGMENT_KAT_TELEPORTATIONMODULE = 400,
        P_CHARAUGMENT_SOFIA_SUPERCHARGEDPROJECTILE = 402,
        P_GIVE_ITEM_SWAPPER = 404,
        P_SPAWNENTITY_TANK = 405,
        P_DOUBLERANDOM = 407,
        P_DRONENATOR = 408,
        P_ONDAMAGE_NOODLECOMBO = 410,
        P_ONDAMAGE_THOUSANDCUTS = 412,
        P_ONTIMER_INVULNERABLE = 415,
        P_PUSHANDPULL = 417,
        P_STAT_NEGATIVECDR = 418, // Used for the "Get two random augments" to give -10 CDR


        P_CUSTOM_AUGMENTTEST = 419,
    }
}
